apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: falco-ai-alerts-hpa
  namespace: falco-ai-alerts
  labels:
    app.kubernetes.io/name: falco-ai-alerts
    app.kubernetes.io/component: autoscaling
    platform: eks
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prod-falco-ai-alerts
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 60 