apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: falco-ai-alerts-dev

resources:
  - ../../base

namespace: falco-ai-alerts-dev

namePrefix: dev-

commonLabels:
  environment: dev
  app.kubernetes.io/version: "2.0.0-dev"

patches:
  # Reduce replicas for development
  - target:
      kind: Deployment
      name: falco-ai-alerts
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  
  # Override storage class for GKE
  - target:
      kind: PersistentVolumeClaim
      name: weaviate-pvc
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: standard-rwo
  
  # Use NodePort for easy local access
  - target:
      kind: Service
      name: falco-ai-alerts
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30080

  # Make webhook service also NodePort for development
  - target:
      kind: Service
      name: falco-ai-alerts-webhook
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30081

  # Reduce resource requests for development
  - target:
      kind: Deployment
      name: falco-ai-alerts
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "100m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "200m"

  # Override ConfigMap values for development
  - target:
      kind: ConfigMap
      name: falco-ai-alerts-config
    patch: |-
      - op: replace
        path: /data/LOG_LEVEL
        value: "DEBUG"
      - op: replace
        path: /data/MIN_PRIORITY
        value: "notice"
      - op: replace
        path: /data/OLLAMA_TIMEOUT
        value: "30"
      - op: replace
        path: /data/AI_REQUEST_TIMEOUT  
        value: "30"
      - op: add
        path: /data/ALERT_RETENTION_DAYS
        value: "7"

  # Fix Ollama service name in init job
  - target:
      kind: Job
      name: ollama-model-init
    patch: |-
      - op: replace
        path: /spec/template/spec/initContainers/0/command/2
        value: |
          echo "Waiting for Ollama service to be ready..."
          until wget -q --spider http://dev-ollama:11434/api/tags; do
            echo "Ollama not ready, waiting 10 seconds..."
            sleep 10
          done
          echo "Ollama is ready!"
      - op: replace
        path: /spec/template/spec/containers/0/command/2
        value: |
          echo "Pulling ultra-fast model: tinyllama"
          curl -X POST http://dev-ollama:11434/api/pull \
            -H "Content-Type: application/json" \
            -d '{"name": "tinyllama"}' \
            --max-time 1800
          
          echo "Verifying model was pulled..."
          curl -s http://dev-ollama:11434/api/tags | grep -q "tinyllama" || exit 1
          
          echo "Warming up model with test inference..."
          curl -X POST http://dev-ollama:11434/api/generate \
            -H "Content-Type: application/json" \
            -d '{"model": "tinyllama", "prompt": "Hello, test", "stream": false}' \
            --max-time 60
          
          echo "Model initialization and warm-up complete!"

  # Development Ollama resource optimization  
  # Use smaller 8B model for development to reduce resource requirements
  - target:
      kind: Deployment
      name: ollama
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "6Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "8Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "1000m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "2000m"

  # Development Weaviate resource optimization
  - target:
      kind: Deployment
      name: weaviate
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "100m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "500m"

  # Development PVC size
  - target:
      kind: PersistentVolumeClaim
      name: ollama-data
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: "15Gi"

  # Development Weaviate PVC size
  - target:
      kind: PersistentVolumeClaim
      name: weaviate-pvc
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: "5Gi"

  # Increase readiness probe timeout for development
  - target:
      kind: Deployment
      name: falco-ai-alerts
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/initialDelaySeconds
        value: 30
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/timeoutSeconds
        value: 10
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe/initialDelaySeconds
        value: 60
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe/timeoutSeconds
        value: 10

  # Fix service names for development environment
  - target:
      kind: ConfigMap
      name: falco-ai-alerts-config
    patch: |-
      - op: replace
        path: /data/OLLAMA_API_URL
        value: "http://dev-ollama:11434/api/generate"
      - op: replace
        path: /data/WEAVIATE_HOST
        value: "dev-weaviate"

images:
  - name: falco-ai-alerts
    newName: maddigsys/falco-ai-alerts
    newTag: v2.0.0-amd64 