apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: falco-ai-alerts-production

resources:
  - ../../base
  - hpa.yaml
  - network-policy.yaml

namespace: falco-ai-alerts

namePrefix: prod-

commonLabels:
  environment: production
  app.kubernetes.io/version: "1.0.0"

patches:
  # Increase replicas for production
  - target:
      kind: Deployment
      name: falco-ai-alerts
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  
  # Increase resource limits for production
  - target:
      kind: Deployment
      name: falco-ai-alerts
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1000m"

  # Add production readiness configurations
  - target:
      kind: Deployment
      name: falco-ai-alerts
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ENVIRONMENT
          value: "production"

configMapGenerator:
  - name: falco-ai-alerts-config
    behavior: merge
    literals:
      - LOG_LEVEL=INFO
      - MIN_PRIORITY=warning
      - ALERT_RETENTION_DAYS=90
      - MAX_ALERTS_STORAGE=100000

images:
  - name: falco-ai-alerts
    newName: maddigsys/falco-ai-alerts
    newTag: "v1.0.0" 