apiVersion: v1
kind: ConfigMap
metadata:
  name: falco-ai-alerts-config
  namespace: falco-ai-alerts
  labels:
    app.kubernetes.io/name: falco-ai-alerts
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: falco-ecosystem
data:
  # Application Configuration
  WEB_UI_ENABLED: "true"
  WEB_UI_PORT: "8081"
  FALCO_AI_PORT: "8080"
  LOG_LEVEL: "INFO"
  
  # Alert Processing
  MIN_PRIORITY: "warning"
  IGNORE_OLDER: "1"
  DEDUPLICATION_ENABLED: "true"
  DEDUPLICATION_WINDOW_MINUTES: "60"
  
  # Database Configuration
  MAX_ALERTS_STORAGE: "10000"
  ALERT_RETENTION_DAYS: "30"
  
  # AI Configuration
  PROVIDER_NAME: "ollama"
  MODEL_NAME: "llama3.1:8b"
  OLLAMA_API_URL: "http://ollama:11434/api/generate"
  OLLAMA_MODEL_NAME: "llama3.1:8b"
  MAX_TOKENS: "500"
  TEMPERATURE: "0.7"
  AI_ENABLED: "true"
  # Timeout configuration (optimized for 8B models for faster, more reliable responses)
  OLLAMA_TIMEOUT: "30"  # seconds - adjusted for 8B model: 8B=30s, 13B=90s, 30B+=120s
  AI_REQUEST_TIMEOUT: "30"  # seconds - application-level timeout
  
  # Slack Configuration
  SLACK_ENABLED: "true"
  SLACK_CHANNEL_NAME: "#security-alerts"
  SLACK_USERNAME: "Falco AI Alerts"
  SLACK_ICON_EMOJI: ":shield:"
  SLACK_TEMPLATE_STYLE: "detailed"
  SLACK_MIN_PRIORITY: "warning"
  SLACK_INCLUDE_COMMANDS: "true"
  SLACK_THREAD_ALERTS: "false" 