apiVersion: v1
kind: ConfigMap
metadata:
  name: falco-vanguard-config
  namespace: falco-vanguard
  labels:
    app.kubernetes.io/name: falco-vanguard
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: falco-ecosystem
data:
  # Application Configuration
  WEB_UI_ENABLED: "true"
  WEB_UI_PORT: "8081"
  FALCO_AI_PORT: "8080"
  LOG_LEVEL: "INFO"
  
  # Alert Processing
  MIN_PRIORITY: "warning"
  IGNORE_OLDER: "1"
  DEDUPLICATION_ENABLED: "true"
  DEDUPLICATION_WINDOW_MINUTES: "60"
  
  # Advanced Alert Processing
  RATE_LIMIT_ENABLED: "false"
  MAX_ALERTS_PER_MINUTE: "60"
  BATCH_PROCESSING_ENABLED: "false"
  BATCH_SIZE: "10"
  ALERT_CORRELATION_ENABLED: "false"
  CORRELATION_WINDOW_MINUTES: "15"
  
  # Database Configuration
  MAX_ALERTS_STORAGE: "10000"
  ALERT_RETENTION_DAYS: "30"
  
  # AI Configuration
  PROVIDER_NAME: "ollama"
  MODEL_NAME: "tinyllama"
  OLLAMA_API_URL: "http://prod-ollama:11434/api/generate"
  OLLAMA_MODEL_NAME: "tinyllama"
  MAX_TOKENS: "500"
  TEMPERATURE: "0.7"
  AI_ENABLED: "true"
  # Timeout configuration (model-specific - adjust based on model size)
  # tinyllama: 30s | phi3:mini: 45s | llama3.1:8b: 60s | cybersecurity models: 90s
  OLLAMA_TIMEOUT: "30"  # seconds - application timeout for AI requests
  AI_REQUEST_TIMEOUT: "30"  # seconds - overall request timeout
  
  # Slack Configuration
  SLACK_ENABLED: "true"
  SLACK_CHANNEL_NAME: "#security-alerts"
  SLACK_USERNAME: "Falco AI Alerts"
  SLACK_ICON_EMOJI: ":shield:"
  SLACK_TEMPLATE_STYLE: "detailed"
  SLACK_MIN_PRIORITY: "warning"
  SLACK_INCLUDE_COMMANDS: "true"
  SLACK_THREAD_ALERTS: "false"
  
  # Advanced Slack Processing
  SLACK_NOTIFICATION_THROTTLING: "false"
  SLACK_THROTTLE_THRESHOLD: "10"
  SLACK_BUSINESS_HOURS_ONLY: "false"
  SLACK_BUSINESS_HOURS: "09:00-17:00"
  SLACK_ESCALATION_ENABLED: "false"
  SLACK_ESCALATION_INTERVAL: "30"
  SLACK_DIGEST_MODE_ENABLED: "false"
  SLACK_DIGEST_TIME: "09:00"
  
  # Weaviate Configuration
  WEAVIATE_HOST: "weaviate"
  WEAVIATE_PORT: "8080"
  WEAVIATE_GRPC_PORT: "50051"
  WEAVIATE_ENABLED: "true" 