apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: falco-ai-alerts-base

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - ollama-deployment.yaml
  - ollama-init-job.yaml

commonLabels:
  app.kubernetes.io/part-of: falco-ecosystem

images:
  - name: falco-ai-alerts
    newName: maddigsys/falco-ai-alerts
    newTag: latest 