apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: falco-ai-alerts
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/component: ai-provider
    app.kubernetes.io/part-of: falco-ecosystem
spec:
  replicas: 1
  strategy:
    type: Recreate  # Ollama needs persistent storage
  selector:
    matchLabels:
      app.kubernetes.io/name: ollama
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ollama
        app.kubernetes.io/component: ai-provider
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
          name: api
          protocol: TCP
        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0"
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /api/tags
            port: api
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/tags
            port: api
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: ollama-data
        persistentVolumeClaim:
          claimName: ollama-data
      securityContext:
        runAsNonRoot: false  # Ollama needs root for GPU access
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: falco-ai-alerts
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/component: ai-provider
spec:
  type: ClusterIP
  ports:
  - name: api
    port: 11434
    targetPort: api
    protocol: TCP
  selector:
    app.kubernetes.io/name: ollama
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data
  namespace: falco-ai-alerts
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi  # Ollama models can be large 