apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: falco-ai-alerts-data
  namespace: falco-ai-alerts
  labels:
    app.kubernetes.io/name: falco-ai-alerts
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: falco-ecosystem
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName will use default storage class 