apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: falco-ai-alerts-data
  namespace: falco-ai-alerts
  labels:
    app.kubernetes.io/name: falco-ai-alerts
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "" # Use default storage class or specify your preferred one 