apiVersion: v1
kind: Secret
metadata:
  name: falco-ai-alerts-secrets
  namespace: falco-ai-alerts
  labels:
    app.kubernetes.io/name: falco-ai-alerts
    app.kubernetes.io/component: configuration
type: Opaque
stringData:
  # Slack Bot Token (replace with your actual token)
  SLACK_BOT_TOKEN: "xoxb-your-slack-bot-token-here"
  
  # AI Provider API Keys (uncomment and fill as needed)
  PORTKEY_API_KEY: "your-portkey-api-key-here"
  OPENAI_VIRTUAL_KEY: "your-openai-virtual-key-here"
  GEMINI_VIRTUAL_KEY: "your-gemini-virtual-key-here"
  
  # Database encryption key (generate a secure random string)
  DB_ENCRYPTION_KEY: "change-me-to-a-secure-random-string" 