apiVersion: v1
kind: Secret
metadata:
  name: falco-vanguard-secrets
  namespace: falco-vanguard
  labels:
    app.kubernetes.io/name: falco-vanguard
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: falco-ecosystem
  annotations:
    description: "Template for Falco Vanguard secrets"
    environment-naming: "Use dev-/prod- prefixes for actual deployments"
type: Opaque
stringData:
  # Slack Bot Token (replace with your actual token)
  # Get from: https://api.slack.com/apps
  SLACK_BOT_TOKEN: "xoxb-your-slack-bot-token-here"
  
  # Portkey Security Layer (required for cloud AI providers)
  # Get from: https://portkey.ai
  PORTKEY_API_KEY: "pk-your-portkey-api-key-here"
  
  # AI Provider Virtual Keys (via Portkey)
  # Get virtual keys from Portkey dashboard after adding providers
  OPENAI_VIRTUAL_KEY: "openai-your-virtual-key-here"
  GEMINI_VIRTUAL_KEY: "gemini-your-virtual-key-here"
  
  # Database encryption key (generate with: openssl rand -base64 32)
  DB_ENCRYPTION_KEY: "change-me-to-a-secure-random-string" 