apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco-ai-alerts
  namespace: falco-ai-alerts
  labels:
    app.kubernetes.io/name: falco-ai-alerts
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: falco-ecosystem
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: falco-ai-alerts
  labels:
    app.kubernetes.io/name: falco-ai-alerts
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: falco-ecosystem
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: falco-ai-alerts
  labels:
    app.kubernetes.io/name: falco-ai-alerts
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: falco-ecosystem
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: falco-ai-alerts
subjects:
- kind: ServiceAccount
  name: falco-ai-alerts
  namespace: falco-ai-alerts 